version: 2
updates:
- package-ecosystem: composer
  directory: "/src"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: docker
  directory: "/docker"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: github-actions
  directory: ".github"
  schedule:
    interval: monthly
  open-pull-requests-limit: 30
  versioning-strategy: increase
