services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app